"""extended_lms_domain

Revision ID: d710a69ed9a0
Revises: b7c8d9e0f1a2
Create Date: 2026-08-26 13:19:59.962246
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd710a69ed9a0'
down_revision: str | None = 'b7c8d9e0f1a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_ai_jobs_institution_id_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_ai_jobs_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ai_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_ai_jobs_institution_id'), 'ai_jobs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_requested_by'), 'ai_jobs', ['requested_by'], unique=False)
    op.create_index('ix_ai_jobs_state', 'ai_jobs', ['status', 'created_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys'))
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('report_kind', sa.String(length=60), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_report_jobs_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_report_jobs_requested_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_report_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_report_jobs_institution_id'), 'report_jobs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_report_jobs_requested_by'), 'report_jobs', ['requested_by'], unique=False)
    op.create_table('ai_runs',
    sa.Column('ai_job_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ai_runs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ai_job_id'], ['ai_jobs.id'], name=op.f('fk_ai_runs_ai_job_id_ai_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_ai_runs_institution_id_institutions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_actor_id'), 'ai_runs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_ai_job_id'), 'ai_runs', ['ai_job_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_input_hash'), 'ai_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_ai_runs_institution_id'), 'ai_runs', ['institution_id'], unique=False)
    op.create_table('grades',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.Uuid(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_grades_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_grades_graded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_grades_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_grades_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades'))
    )
    op.create_index(op.f('ix_grades_course_id'), 'grades', ['course_id'], unique=False)
    op.create_index('ix_grades_current', 'grades', ['student_id', 'item_type', 'item_id'], unique=True)
    op.create_index(op.f('ix_grades_institution_id'), 'grades', ['institution_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('learning_objectives',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_learning_objectives_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_learning_objectives_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['learning_objectives.id'], name=op.f('fk_learning_objectives_parent_id_learning_objectives'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_objectives'))
    )
    op.create_index(op.f('ix_learning_objectives_course_id'), 'learning_objectives', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_objectives_institution_id'), 'learning_objectives', ['institution_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_source_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notification_deliveries_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('event_type', 'event_source_id', 'recipient_id', name='uq_notif_delivery_dedup')
    )
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_recipient_id'), 'notification_deliveries', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_scheduled_for'), 'notification_deliveries', ['scheduled_for'], unique=False)
    op.create_table('notification_recipient_states',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_recipient_states_notification_id_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notification_recipient_states_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_recipient_states')),
    sa.UniqueConstraint('notification_id', 'recipient_id', name='uq_notif_recipient')
    )
    op.create_index(op.f('ix_notification_recipient_states_notification_id'), 'notification_recipient_states', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_recipient_states_recipient_id'), 'notification_recipient_states', ['recipient_id'], unique=False)
    op.create_table('question_banks',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_question_banks_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_question_banks_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_banks'))
    )
    op.create_index(op.f('ix_question_banks_course_id'), 'question_banks', ['course_id'], unique=False)
    op.create_index(op.f('ix_question_banks_institution_id'), 'question_banks', ['institution_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_risk_assessments_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_risk_assessments_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_risk_assessments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_course_id'), 'risk_assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_institution_id'), 'risk_assessments', ['institution_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_student_id'), 'risk_assessments', ['student_id'], unique=False)
    op.create_index('ix_risk_student_latest', 'risk_assessments', ['student_id', 'created_at'], unique=False)
    op.create_table('chapters',
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_chapters_module_id_course_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('module_id', 'position', name='uq_chapter_module_position')
    )
    op.create_index(op.f('ix_chapters_module_id'), 'chapters', ['module_id'], unique=False)
    op.create_table('interventions',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('risk_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_interventions_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_interventions_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], name=op.f('fk_interventions_risk_assessment_id_risk_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_interventions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    op.create_index(op.f('ix_interventions_institution_id'), 'interventions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_interventions_risk_assessment_id'), 'interventions', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_interventions_student_id'), 'interventions', ['student_id'], unique=False)
    op.create_table('question_versions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_versions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_versions')),
    sa.UniqueConstraint('question_id', 'version', name='uq_question_version_number')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_rubrics_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rubrics_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics'))
    )
    op.create_index(op.f('ix_rubrics_assignment_id'), 'rubrics', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_rubrics_institution_id'), 'rubrics', ['institution_id'], unique=False)
    op.create_table('student_mastery',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mastery BETWEEN 0 AND 1', name=op.f('ck_student_mastery_ck_mastery_range')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_student_mastery_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['learning_objectives.id'], name=op.f('fk_student_mastery_objective_id_learning_objectives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_mastery_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_mastery')),
    sa.UniqueConstraint('student_id', 'objective_id', name='uq_mastery_student_objective')
    )
    op.create_index(op.f('ix_student_mastery_institution_id'), 'student_mastery', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_objective_id'), 'student_mastery', ['objective_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_student_id'), 'student_mastery', ['student_id'], unique=False)
    op.create_table('lesson_assets',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('asset_kind', sa.String(length=40), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_lesson_assets_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_assets_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_assets'))
    )
    op.create_index(op.f('ix_lesson_assets_institution_id'), 'lesson_assets', ['institution_id'], unique=False)
    op.create_index(op.f('ix_lesson_assets_lesson_id'), 'lesson_assets', ['lesson_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], name=op.f('fk_rubric_criteria_rubric_id_rubrics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_criteria'))
    )
    op.create_index(op.f('ix_rubric_criteria_rubric_id'), 'rubric_criteria', ['rubric_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: intentional no-op for certificates/revoked_sessions/users.role/video_events:
    # autogenerate detected cosmetic unique-index/type drift between legacy migrations
    # and current models; the runtime constraints are already correct. Keeping this
    # migration purely additive avoids destructive churn on existing databases.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_criteria_rubric_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_lesson_assets_lesson_id'), table_name='lesson_assets')
    op.drop_index(op.f('ix_lesson_assets_institution_id'), table_name='lesson_assets')
    op.drop_table('lesson_assets')
    op.drop_index(op.f('ix_student_mastery_student_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_objective_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_institution_id'), table_name='student_mastery')
    op.drop_table('student_mastery')
    op.drop_index(op.f('ix_rubrics_institution_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_assignment_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_index(op.f('ix_interventions_student_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_risk_assessment_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_institution_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_chapters_module_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('ix_risk_student_latest', table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_student_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_institution_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_course_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_question_banks_institution_id'), table_name='question_banks')
    op.drop_index(op.f('ix_question_banks_course_id'), table_name='question_banks')
    op.drop_table('question_banks')
    op.drop_index(op.f('ix_notification_recipient_states_recipient_id'), table_name='notification_recipient_states')
    op.drop_index(op.f('ix_notification_recipient_states_notification_id'), table_name='notification_recipient_states')
    op.drop_table('notification_recipient_states')
    op.drop_index(op.f('ix_notification_deliveries_scheduled_for'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_recipient_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_learning_objectives_institution_id'), table_name='learning_objectives')
    op.drop_index(op.f('ix_learning_objectives_course_id'), table_name='learning_objectives')
    op.drop_table('learning_objectives')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_institution_id'), table_name='grades')
    op.drop_index('ix_grades_current', table_name='grades')
    op.drop_index(op.f('ix_grades_course_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_ai_runs_institution_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_input_hash'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_ai_job_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_actor_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_report_jobs_requested_by'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_jobs_institution_id'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_ai_jobs_state', table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_requested_by'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_institution_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
