"""add_knowledge_center_and_question_records

Revision ID: f03ae2a24ae2
Revises: d710a69ed9a0
Create Date: 2026-09-05 19:20:21.657065
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f03ae2a24ae2'
down_revision: str | None = 'd710a69ed9a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_refusal_logs',
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_ai_refusal_logs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_ai_refusal_logs_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_refusal_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_refusal_logs'))
    )
    op.create_index(op.f('ix_ai_refusal_logs_course_id'), 'ai_refusal_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_refusal_logs_institution_id'), 'ai_refusal_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_refusal_logs_user_id'), 'ai_refusal_logs', ['user_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=30), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_role', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_knowledge_sources_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_knowledge_sources_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_knowledge_sources_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_knowledge_sources_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index(op.f('ix_knowledge_sources_checksum'), 'knowledge_sources', ['checksum'], unique=False)
    op.create_index('ix_knowledge_sources_course', 'knowledge_sources', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_course_id'), 'knowledge_sources', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_institution_id'), 'knowledge_sources', ['institution_id'], unique=False)
    op.create_index('ix_knowledge_sources_lesson', 'knowledge_sources', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_lesson_id'), 'knowledge_sources', ['lesson_id'], unique=False)
    op.create_index('ix_knowledge_sources_status', 'knowledge_sources', ['status'], unique=False)
    op.create_index('ix_knowledge_sources_teacher', 'knowledge_sources', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_teacher_id'), 'knowledge_sources', ['teacher_id'], unique=False)
    op.create_table('transcription_jobs',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('remote_job_id', sa.String(length=120), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('signed_download_token_hash', sa.String(length=128), nullable=False),
    sa.Column('signed_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('callback_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('artifact_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('coverage_ratio', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_transcription_jobs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_transcription_jobs_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcription_jobs'))
    )
    op.create_index('ix_transcription_jobs_course', 'transcription_jobs', ['course_id'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_course_id'), 'transcription_jobs', ['course_id'], unique=False)
    op.create_index('ix_transcription_jobs_lesson', 'transcription_jobs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_lesson_id'), 'transcription_jobs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_signed_download_token_hash'), 'transcription_jobs', ['signed_download_token_hash'], unique=False)
    op.create_index('ix_transcription_jobs_status', 'transcription_jobs', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_model', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_transcripts_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('lesson_id', name='uq_transcripts_lesson_id')
    )
    op.create_index(op.f('ix_transcripts_lesson_id'), 'transcripts', ['lesson_id'], unique=False)
    op.create_index('ix_transcripts_status', 'transcripts', ['status'], unique=False)
    op.create_table('assessment_sources',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_assessment_sources_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_sources'))
    )
    op.create_index(op.f('ix_assessment_sources_source_id'), 'assessment_sources', ['source_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_knowledge_chunks_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_knowledge_chunks_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_knowledge_chunks_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('transcript_id', 'sequence', name='uq_knowledge_chunks_seq')
    )
    op.create_index('ix_knowledge_chunks_course', 'knowledge_chunks', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_course_id'), 'knowledge_chunks', ['course_id'], unique=False)
    op.create_index('ix_knowledge_chunks_lesson', 'knowledge_chunks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_lesson_id'), 'knowledge_chunks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_transcript_id'), 'knowledge_chunks', ['transcript_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('total_slides', sa.Integer(), nullable=False),
    sa.Column('hierarchy_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_documents_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_source_id'), 'knowledge_documents', ['source_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_transcript_segments_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_transcript_segments_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segments')),
    sa.UniqueConstraint('transcript_id', 'sequence', name='uq_transcript_segments_seq')
    )
    op.create_index('ix_transcript_segments_lesson', 'transcript_segments', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_lesson_id'), 'transcript_segments', ['lesson_id'], unique=False)
    op.create_index('ix_transcript_segments_time', 'transcript_segments', ['transcript_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_source_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('learning_objective', sa.String(length=100), nullable=False),
    sa.Column('topic_concept', sa.String(length=255), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('media_ids_json', sa.JSON(), nullable=True),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('semantic_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_source_id'], ['assessment_sources.id'], name=op.f('fk_assessment_questions_assessment_source_id_assessment_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assessment_questions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_assessment_questions_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions'))
    )
    op.create_index(op.f('ix_assessment_questions_assessment_source_id'), 'assessment_questions', ['assessment_source_id'], unique=False)
    op.create_index('ix_assessment_questions_course', 'assessment_questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_course_id'), 'assessment_questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_lesson_id'), 'assessment_questions', ['lesson_id'], unique=False)
    op.create_index('ix_assessment_questions_norm_hash', 'assessment_questions', ['normalized_hash'], unique=False)
    op.create_index(op.f('ix_assessment_questions_normalized_hash'), 'assessment_questions', ['normalized_hash'], unique=False)
    op.create_index(op.f('ix_assessment_questions_semantic_fingerprint'), 'assessment_questions', ['semantic_fingerprint'], unique=False)
    op.create_index('ix_assessment_questions_source', 'assessment_questions', ['assessment_source_id'], unique=False)
    op.create_table('knowledge_assets',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('asset_kind', sa.String(length=40), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_assets_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_assets_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_assets'))
    )
    op.create_index(op.f('ix_knowledge_assets_checksum'), 'knowledge_assets', ['checksum'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_document_id'), 'knowledge_assets', ['document_id'], unique=False)
    op.create_index('ix_knowledge_assets_kind', 'knowledge_assets', ['asset_kind'], unique=False)
    op.create_index('ix_knowledge_assets_source', 'knowledge_assets', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_assets_source_id'), 'knowledge_assets', ['source_id'], unique=False)
    op.create_table('knowledge_question_records',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('image_asset_ids_json', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('classification_confidence', sa.String(length=20), nullable=False),
    sa.Column('needs_answer_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_knowledge_question_records_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_question_records_document_id_knowledge_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_knowledge_question_records_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_question_records_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_question_records'))
    )
    op.create_index(op.f('ix_knowledge_question_records_course_id'), 'knowledge_question_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_question_records_document_id'), 'knowledge_question_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_question_records_lesson_id'), 'knowledge_question_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_question_records_source_id'), 'knowledge_question_records', ['source_id'], unique=False)
    op.create_index('ix_kq_records_course', 'knowledge_question_records', ['course_id'], unique=False)
    op.create_index('ix_kq_records_lesson', 'knowledge_question_records', ['lesson_id'], unique=False)
    op.create_index('ix_kq_records_source', 'knowledge_question_records', ['source_id'], unique=False)
    op.create_table('knowledge_units_records',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('knowledge_type', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('entities_json', sa.JSON(), nullable=True),
    sa.Column('relationships_json', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('semantic_confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.String(length=100), nullable=True),
    sa.Column('source_segment_ids_json', sa.JSON(), nullable=True),
    sa.Column('source_media_ids_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_knowledge_units_records_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_knowledge_units_records_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_units_records_source_document_id_knowledge_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_units_records_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_units_records'))
    )
    op.create_index(op.f('ix_knowledge_units_records_course_id'), 'knowledge_units_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_units_records_lesson_id'), 'knowledge_units_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_units_records_source_id'), 'knowledge_units_records', ['source_id'], unique=False)
    op.create_index('ix_ku_records_concept', 'knowledge_units_records', ['concept'], unique=False)
    op.create_index('ix_ku_records_course', 'knowledge_units_records', ['course_id'], unique=False)
    op.create_index('ix_ku_records_lesson', 'knowledge_units_records', ['lesson_id'], unique=False)
    op.create_index('ix_ku_records_source', 'knowledge_units_records', ['source_id'], unique=False)
    op.create_table('assessment_question_usages',
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('usage_context', sa.String(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_assessment_question_usages_assignment_id_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assessment_question_usages_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_assessment_question_usages_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name=op.f('fk_assessment_question_usages_question_id_assessment_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_assessment_question_usages_quiz_id_quizzes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_question_usages'))
    )
    op.create_index(op.f('ix_assessment_question_usages_assignment_id'), 'assessment_question_usages', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_usages_course_id'), 'assessment_question_usages', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_usages_lesson_id'), 'assessment_question_usages', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_usages_question_id'), 'assessment_question_usages', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_question_usages_quiz_id'), 'assessment_question_usages', ['quiz_id'], unique=False)
    op.create_index('ix_question_usages_course', 'assessment_question_usages', ['course_id'], unique=False)
    op.create_index('ix_question_usages_question', 'assessment_question_usages', ['question_id'], unique=False)
    with op.batch_alter_table('lessons') as batch_op:
        batch_op.add_column(sa.Column('indexing_status', sa.Enum('not_indexed', 'in_progress', 'indexed', 'failed', name='indexing_status', native_enum=False), nullable=False, server_default='not_indexed'))
        batch_op.add_column(sa.Column('indexing_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('indexed_chunks_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('transcript_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rag_synced', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons') as batch_op:
        batch_op.drop_column('rag_synced')
        batch_op.drop_column('transcript_text')
        batch_op.drop_column('indexed_chunks_count')
        batch_op.drop_column('indexing_error')
        batch_op.drop_column('indexing_status')
    op.drop_index('ix_question_usages_question', table_name='assessment_question_usages')
    op.drop_index('ix_question_usages_course', table_name='assessment_question_usages')
    op.drop_index(op.f('ix_assessment_question_usages_quiz_id'), table_name='assessment_question_usages')
    op.drop_index(op.f('ix_assessment_question_usages_question_id'), table_name='assessment_question_usages')
    op.drop_index(op.f('ix_assessment_question_usages_lesson_id'), table_name='assessment_question_usages')
    op.drop_index(op.f('ix_assessment_question_usages_course_id'), table_name='assessment_question_usages')
    op.drop_index(op.f('ix_assessment_question_usages_assignment_id'), table_name='assessment_question_usages')
    op.drop_table('assessment_question_usages')
    op.drop_index('ix_ku_records_source', table_name='knowledge_units_records')
    op.drop_index('ix_ku_records_lesson', table_name='knowledge_units_records')
    op.drop_index('ix_ku_records_course', table_name='knowledge_units_records')
    op.drop_index('ix_ku_records_concept', table_name='knowledge_units_records')
    op.drop_index(op.f('ix_knowledge_units_records_source_id'), table_name='knowledge_units_records')
    op.drop_index(op.f('ix_knowledge_units_records_lesson_id'), table_name='knowledge_units_records')
    op.drop_index(op.f('ix_knowledge_units_records_course_id'), table_name='knowledge_units_records')
    op.drop_table('knowledge_units_records')
    op.drop_index('ix_kq_records_source', table_name='knowledge_question_records')
    op.drop_index('ix_kq_records_lesson', table_name='knowledge_question_records')
    op.drop_index('ix_kq_records_course', table_name='knowledge_question_records')
    op.drop_index(op.f('ix_knowledge_question_records_source_id'), table_name='knowledge_question_records')
    op.drop_index(op.f('ix_knowledge_question_records_lesson_id'), table_name='knowledge_question_records')
    op.drop_index(op.f('ix_knowledge_question_records_document_id'), table_name='knowledge_question_records')
    op.drop_index(op.f('ix_knowledge_question_records_course_id'), table_name='knowledge_question_records')
    op.drop_table('knowledge_question_records')
    op.drop_index(op.f('ix_knowledge_assets_source_id'), table_name='knowledge_assets')
    op.drop_index('ix_knowledge_assets_source', table_name='knowledge_assets')
    op.drop_index('ix_knowledge_assets_kind', table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_document_id'), table_name='knowledge_assets')
    op.drop_index(op.f('ix_knowledge_assets_checksum'), table_name='knowledge_assets')
    op.drop_table('knowledge_assets')
    op.drop_index('ix_assessment_questions_source', table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_semantic_fingerprint'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_normalized_hash'), table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_norm_hash', table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_lesson_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_course_id'), table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_course', table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_source_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_index('ix_transcript_segments_time', table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_lesson_id'), table_name='transcript_segments')
    op.drop_index('ix_transcript_segments_lesson', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_knowledge_documents_source_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_chunks_transcript_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_lesson_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_lesson', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_course_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_course', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_assessment_sources_source_id'), table_name='assessment_sources')
    op.drop_table('assessment_sources')
    op.drop_index('ix_transcripts_status', table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_lesson_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_transcription_jobs_status', table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_signed_download_token_hash'), table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_lesson_id'), table_name='transcription_jobs')
    op.drop_index('ix_transcription_jobs_lesson', table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_course_id'), table_name='transcription_jobs')
    op.drop_index('ix_transcription_jobs_course', table_name='transcription_jobs')
    op.drop_table('transcription_jobs')
    op.drop_index(op.f('ix_knowledge_sources_teacher_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_teacher', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_status', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_lesson_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_lesson', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_institution_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_course_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_course', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_checksum'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_ai_refusal_logs_user_id'), table_name='ai_refusal_logs')
    op.drop_index(op.f('ix_ai_refusal_logs_institution_id'), table_name='ai_refusal_logs')
    op.drop_index(op.f('ix_ai_refusal_logs_course_id'), table_name='ai_refusal_logs')
    op.drop_table('ai_refusal_logs')
    # ### end Alembic commands ###
